

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString *const THD_GAME_START;
FOUNDATION_EXPORT NSString *const THD_GAME_KEYMOMENT;
FOUNDATION_EXPORT NSString *const THD_NEWUSER_TUTORIAL;
FOUNDATION_EXPORT NSString *const THD_USER_REGISTRATION;
FOUNDATION_EXPORT NSString *const THD_USER_LOGIN;
FOUNDATION_EXPORT NSString *const THD_APP_PUSHSTART;
FOUNDATION_EXPORT NSString *const THD_LEVEL_ACHIEVED;
FOUNDATION_EXPORT NSString *const THD_LEVEL_START;
FOUNDATION_EXPORT NSString *const THD_LEVEL_END;
FOUNDATION_EXPORT NSString *const THD_CREDITS_EARN;
FOUNDATION_EXPORT NSString *const THD_CREDITS_SPEND;
FOUNDATION_EXPORT NSString *const THD_COINS_EARN;
FOUNDATION_EXPORT NSString *const THD_COINS_SPEND;
FOUNDATION_EXPORT NSString *const THD_ACHIEVEMENT_UNLOCKED;
FOUNDATION_EXPORT NSString *const THD_INVITE;
FOUNDATION_EXPORT NSString *const THD_SHARE;
FOUNDATION_EXPORT NSString *const THD_PURCHASE;
FOUNDATION_EXPORT NSString *const THD_ADDTOCART;
FOUNDATION_EXPORT NSString *const THD_AD_IMPRESS;
FOUNDATION_EXPORT NSString *const THD_AD_CLICK;
FOUNDATION_EXPORT NSString *const MAG_LTV1day_Top10Percent;
FOUNDATION_EXPORT NSString *const MAG_LTV1day_Top20Percent;
FOUNDATION_EXPORT NSString *const MAG_LTV1day_Top30Percent;
FOUNDATION_EXPORT NSString *const MAG_LTV1day_Top40Percent;
FOUNDATION_EXPORT NSString *const MAG_LTV1day_Top50Percent;
FOUNDATION_EXPORT NSString *const MAG_TOTAL_REVENUE001;
